import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import { AccountProvider } from "./context/AccountContext";
import { SWRProvider } from "./lib/swrConfig";
import 'bootstrap/dist/css/bootstrap.min.css';
import { ReduxProvider } from "./providers/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReduxProvider>
          <SWRProvider >
            <AuthProvider>
              <AccountProvider>{children}</AccountProvider>
            </AuthProvider>
          </SWRProvider>
        </ReduxProvider>

      </body>
    </html>
  );
}
